(function () {
  'use strict';
  if ('serviceWorker' in navigator) window.addEventListener('load', function () { navigator.serviceWorker.register('service-worker.js'); });
  const formatTime = seconds => { const minutes = Math.round(seconds / 60); return minutes ? minutes + ' min' : 'Less than a minute'; };
  const date = value => value ? new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) : 'Not played yet';
  const icon = item => `<span class="achievement-icon" aria-hidden="true">${item.title.charAt(0)}</span>`;
  function card(item, unlocked, p) { const progress = WebArcadeAchievements.progress(item, p); const status = unlocked ? `Unlocked ${date(unlocked)}` : progress ? `${progress[0]} / ${progress[1]}` : 'Locked'; return `<article class="achievement-card ${unlocked ? 'is-unlocked' : 'is-locked'}">${icon(item)}<div><h3>${item.title}</h3><p>${item.description}</p>${progress && !unlocked ? `<progress max="${progress[1]}" value="${progress[0]}"></progress>` : ''}<small>${status}</small></div></article>`; }
  function renderPreview() { const target = document.getElementById('achievement-preview'); if (!target) return; const p = WebArcadeStats.get().pong, unlocked = WebArcadeAchievements.get().unlocked, count = Object.keys(unlocked).length; if (!p.matchesStarted) { target.innerHTML = '<div class="achievement-empty"><strong>Your arcade story starts with a serve.</strong><p>Play Pong to record local statistics and unlock achievements.</p></div>'; return; } const recent = Object.entries(unlocked).sort((a,b) => b[1].localeCompare(a[1])).slice(0, 2).map(([id]) => WebArcadeAchievements.definitions.find(x => x.id === id).title).join(' · '); target.innerHTML = `<div class="summary-grid"><div><strong>${p.matchesWon}–${p.matchesLost}</strong><span>Matches won / lost</span></div><div><strong>${p.currentWinStreak} / ${p.bestWinStreak}</strong><span>Current / best streak</span></div><div><strong>${p.playerPoints + p.cpuPoints}</strong><span>Total points</span></div><div><strong>${count} / ${WebArcadeAchievements.definitions.length}</strong><span>Achievements</span></div></div>${recent ? `<p class="recent-unlocks">Recently unlocked: <strong>${recent}</strong></p>` : ''}`; }
  function modal() { const node = document.createElement('div'); node.className='achievement-modal'; node.id='achievement-modal'; node.hidden=true; node.setAttribute('role','dialog'); node.setAttribute('aria-modal','true'); node.setAttribute('aria-labelledby','achievement-modal-title'); node.innerHTML='<div class="achievement-dialog"><header><div><p class="settings-kicker">ON THIS DEVICE</p><h2 id="achievement-modal-title">Pong progress</h2></div><button type="button" class="settings-close" aria-label="Close statistics">×</button></header><div class="achievement-content"></div></div>'; document.body.append(node); const close=()=>{node.hidden=true;document.body.classList.remove('modal-open');node._opener&&node._opener.focus();}; node.querySelector('.settings-close').onclick=close; node.onclick=e=>{if(e.target===node)close();}; node.addEventListener('keydown',e=>{if(e.key==='Escape')close();}); return node; }
  const dialog=modal();
  function renderDialog() { const p=WebArcadeStats.get().pong, unlocked=WebArcadeAchievements.get().unlocked, count=Object.keys(unlocked).length; const has=p.matchesStarted; dialog.querySelector('.achievement-content').innerHTML=`<p class="local-note">All statistics and achievements are stored only in this browser on this device. Clearing browser data may remove them.</p>${has ? `<div class="summary-grid detailed"><div><strong>${p.matchesStarted}</strong><span>Matches started</span></div><div><strong>${p.matchesCompleted}</strong><span>Matches completed</span></div><div><strong>${p.matchesWon}–${p.matchesLost}</strong><span>Won / lost</span></div><div><strong>${p.playerPoints}–${p.cpuPoints}</strong><span>Player / CPU points</span></div><div><strong>${p.currentWinStreak} / ${p.bestWinStreak}</strong><span>Current / best streak</span></div><div><strong>${formatTime(p.playTimeSeconds)}</strong><span>Approx. play time</span></div></div><p class="stats-detail">Wins by difficulty — Easy ${p.winsByDifficulty.easy}, Normal ${p.winsByDifficulty.normal}, Hard ${p.winsByDifficulty.hard}. Losses — Easy ${p.lossesByDifficulty.easy}, Normal ${p.lossesByDifficulty.normal}, Hard ${p.lossesByDifficulty.hard}. Last played: ${date(p.lastPlayed)}.</p>` : '<div class="achievement-empty"><strong>No Pong matches recorded yet.</strong><p>Start a match to build local statistics. No sample data is shown.</p></div>'}<h3 class="achievement-total">Achievements <span>${count} / ${WebArcadeAchievements.definitions.length}</span></h3><div class="achievement-list">${WebArcadeAchievements.definitions.map(x=>card(x,unlocked[x.id],p)).join('')}</div>`; }
  document.querySelectorAll('[data-achievements-open]').forEach(button=>button.onclick=()=>{renderDialog();dialog.hidden=false;document.body.classList.add('modal-open');dialog._opener=button;dialog.querySelector('.settings-close').focus();});
  window.addEventListener('webarcade:statschange', renderPreview); window.addEventListener('webarcade:achievementschange', renderPreview); renderPreview();
}());
