(() => {
  'use strict';
  const canvas = document.getElementById('pong'), ctx = canvas.getContext('2d');
  const ui = { player: document.getElementById('player-score'), cpu: document.getElementById('cpu-score'), overlay: document.getElementById('overlay'), title: document.getElementById('overlay-title'), copy: document.getElementById('overlay-copy'), action: document.getElementById('main-action'), pause: document.getElementById('pause'), restart: document.getElementById('restart'), mute: document.getElementById('mute') };
  const W = canvas.width, H = canvas.height, paddle = { w: 15, h: 105 }, keys = new Set();
  const levels = { easy: { cpu: 3.4, reaction: .035 }, normal: { cpu: 5.1, reaction: .06 }, hard: { cpu: 7.1, reaction: .1 } };
  let difficulty = localStorage.getItem('web-arcade-pong-difficulty') || 'normal';
  let muted = localStorage.getItem('web-arcade-pong-muted') === 'true', running = false, paused = false, gameOver = false, animation, audio;
  const state = { playerY: (H - paddle.h) / 2, cpuY: (H - paddle.h) / 2, ball: { x: W / 2, y: H / 2, r: 10, vx: 0, vy: 0 }, playerScore: 0, cpuScore: 0 };
  function sound(type) { if (muted || !window.AudioContext) return; audio ||= new AudioContext(); if (audio.state === 'suspended') audio.resume(); const o = audio.createOscillator(), g = audio.createGain(); o.type = type === 'score' ? 'square' : 'sine'; o.frequency.value = type === 'score' ? 180 : 420; g.gain.setValueAtTime(.06, audio.currentTime); g.gain.exponentialRampToValueAtTime(.001, audio.currentTime + .11); o.connect(g).connect(audio.destination); o.start(); o.stop(audio.currentTime + .12); }
  function setDifficulty(level) { difficulty = level; localStorage.setItem('web-arcade-pong-difficulty', level); document.querySelectorAll('[data-level]').forEach(button => button.classList.toggle('active', button.dataset.level === level)); }
  function resetBall(direction = Math.random() > .5 ? 1 : -1) { const b = state.ball; b.x = W / 2; b.y = H / 2; b.vx = direction * 6.1; b.vy = (Math.random() * 5 - 2.5); }
  function resetMatch() { state.playerScore = state.cpuScore = 0; state.playerY = state.cpuY = (H - paddle.h) / 2; ui.player.textContent = '0'; ui.cpu.textContent = '0'; gameOver = false; resetBall(); }
  function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
  function score(player) { if (player) state.playerScore++; else state.cpuScore++; ui.player.textContent = state.playerScore; ui.cpu.textContent = state.cpuScore; sound('score'); if (state.playerScore === 7 || state.cpuScore === 7) { running = false; gameOver = true; ui.pause.disabled = true; ui.overlay.hidden = false; const win = state.playerScore === 7; ui.title.textContent = win ? 'YOU WIN!' : 'CPU WINS'; ui.copy.textContent = win ? 'A perfect neon rally. Ready for another round?' : 'The CPU got there first. Give it another serve.'; ui.action.textContent = 'Play again'; return; } resetBall(player ? -1 : 1); }
  function movePlayer(direction) { state.playerY = clamp(state.playerY + direction * 8.5, 0, H - paddle.h); }
  function update() { if (!running || paused) return; if (keys.has('w') || keys.has('arrowup')) movePlayer(-1); if (keys.has('s') || keys.has('arrowdown')) movePlayer(1); const b = state.ball, cfg = levels[difficulty]; const target = b.y - paddle.h / 2; state.cpuY += clamp(target - state.cpuY, -cfg.cpu, cfg.cpu) * cfg.reaction; state.cpuY = clamp(state.cpuY, 0, H - paddle.h); b.x += b.vx; b.y += b.vy; if (b.y - b.r < 0 || b.y + b.r > H) { b.vy *= -1; b.y = clamp(b.y, b.r, H - b.r); sound('wall'); }
    const hitLeft = b.vx < 0 && b.x - b.r <= 42 + paddle.w && b.x + b.r >= 42 && b.y >= state.playerY && b.y <= state.playerY + paddle.h;
    const hitRight = b.vx > 0 && b.x + b.r >= W - 42 - paddle.w && b.x - b.r <= W - 42 && b.y >= state.cpuY && b.y <= state.cpuY + paddle.h;
    if (hitLeft || hitRight) { const y = hitLeft ? state.playerY : state.cpuY, offset = (b.y - (y + paddle.h / 2)) / (paddle.h / 2); b.vx = (hitLeft ? 1 : -1) * Math.min(Math.abs(b.vx) + .35, 12); b.vy = offset * 7; b.x = hitLeft ? 42 + paddle.w + b.r : W - 42 - paddle.w - b.r; sound('hit'); }
    if (b.x < -b.r) score(false); if (b.x > W + b.r) score(true);
  }
  function draw() { ctx.clearRect(0, 0, W, H); ctx.fillStyle = '#0b0923'; ctx.fillRect(0, 0, W, H); ctx.strokeStyle = '#5e538833'; ctx.setLineDash([12, 15]); ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(W / 2, 0); ctx.lineTo(W / 2, H); ctx.stroke(); ctx.setLineDash([]); const p = state; ctx.shadowBlur = 18; ctx.shadowColor = '#22e6ff'; ctx.fillStyle = '#dffcff'; ctx.fillRect(42, p.playerY, paddle.w, paddle.h); ctx.shadowColor = '#ff3ed1'; ctx.fillStyle = '#ffd9f5'; ctx.fillRect(W - 42 - paddle.w, p.cpuY, paddle.w, paddle.h); ctx.shadowColor = '#bcff3f'; ctx.fillStyle = '#bcff3f'; ctx.beginPath(); ctx.arc(p.ball.x, p.ball.y, p.ball.r, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; }
  function loop() { update(); draw(); animation = requestAnimationFrame(loop); }
  function start() { if (gameOver) resetMatch(); running = true; paused = false; ui.overlay.hidden = true; ui.pause.disabled = false; ui.pause.textContent = 'Pause'; }
  function pause() { if (!running) return; paused = !paused; ui.pause.textContent = paused ? 'Resume' : 'Pause'; ui.overlay.hidden = !paused; if (paused) { ui.title.textContent = 'PAUSED'; ui.copy.textContent = 'Take a breath, then get back in the game.'; ui.action.textContent = 'Resume'; } }
  function setPaddleFromPointer(event) { const rect = canvas.getBoundingClientRect(); const clientY = event.touches ? event.touches[0].clientY : event.clientY; state.playerY = clamp((clientY - rect.top) * H / rect.height - paddle.h / 2, 0, H - paddle.h); }
  document.querySelectorAll('[data-level]').forEach(button => button.addEventListener('click', () => setDifficulty(button.dataset.level)));
  ui.action.addEventListener('click', start); ui.pause.addEventListener('click', pause); ui.restart.addEventListener('click', () => { resetMatch(); running = false; paused = false; ui.pause.disabled = true; ui.overlay.hidden = false; ui.title.textContent = 'SERVE IT UP'; ui.copy.textContent = 'First to seven wins. Keep the rally alive.'; ui.action.textContent = 'Start game'; });
  ui.mute.addEventListener('click', () => { muted = !muted; localStorage.setItem('web-arcade-pong-muted', muted); ui.mute.setAttribute('aria-pressed', muted); ui.mute.innerHTML = muted ? '🔇 <span>Sound off</span>' : '🔊 <span>Sound on</span>'; });
  window.addEventListener('keydown', event => { const key = event.key.toLowerCase(); if (['w','s','arrowup','arrowdown'].includes(key)) { keys.add(key); event.preventDefault(); } }); window.addEventListener('keyup', event => keys.delete(event.key.toLowerCase()));
  canvas.addEventListener('mousemove', setPaddleFromPointer); canvas.addEventListener('touchstart', event => { setPaddleFromPointer(event); event.preventDefault(); }, { passive: false }); canvas.addEventListener('touchmove', event => { setPaddleFromPointer(event); event.preventDefault(); }, { passive: false });
  [['up', -1], ['down', 1]].forEach(([id, direction]) => { const button = document.getElementById(id); const startMove = event => { event.preventDefault(); keys.add(direction === -1 ? 'arrowup' : 'arrowdown'); }; const stopMove = () => keys.delete(direction === -1 ? 'arrowup' : 'arrowdown'); ['pointerdown'].forEach(type => button.addEventListener(type, startMove)); ['pointerup','pointercancel','pointerleave'].forEach(type => button.addEventListener(type, stopMove)); });
  setDifficulty(difficulty); ui.mute.setAttribute('aria-pressed', muted); if (muted) ui.mute.innerHTML = '🔇 <span>Sound off</span>'; resetBall(); draw(); animation = requestAnimationFrame(loop);
  if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('../../service-worker.js', { scope: '../../' }));
})();
