(() => {
  'use strict';
  const key = 'webArcade.patrolChart';
  const defaultData = { version: 2, anchor: '', firstBreak: 2, vacations: [], notes: {} };
  const read = () => { try { const saved = JSON.parse(localStorage.getItem(key)); return { ...defaultData, ...(saved && typeof saved === 'object' ? saved : {}), vacations: Array.isArray(saved && saved.vacations) ? saved.vacations : [], notes: saved && saved.notes && typeof saved.notes === 'object' && !Array.isArray(saved.notes) ? saved.notes : {} }; } catch (_) { return { ...defaultData }; } };
  let data = read(), display = new Date(), activeDate = '', opener = null, editingVacation = [];
  display = new Date(display.getFullYear(), display.getMonth(), 1);
  const grid = document.getElementById('calendar-grid'), title = document.getElementById('month-title'), note = document.getElementById('calendar-note');
  const form = document.getElementById('schedule-form'), anchorInput = document.getElementById('anchor-date');
  const vacationForm = document.getElementById('vacation-form'), vacationStart = document.getElementById('vacation-start'), vacationEnd = document.getElementById('vacation-end'), vacationList = document.getElementById('vacation-list');
  const announce = message => { const node = document.querySelector('[data-announcements]'); if (node) node.textContent = message; };
  const iso = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
  const utcDay = value => Math.floor(Date.UTC(value.getFullYear(), value.getMonth(), value.getDate()) / 86400000);
  const parseISO = value => { const [year, month, day] = value.split('-').map(Number); return new Date(year, month - 1, day); };
  const mod = (value, divisor) => ((value % divisor) + divisor) % divisor;
  const dateLabel = date => new Intl.DateTimeFormat(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }).format(date);
  const shortDate = value => new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(parseISO(value));
  function stateFor(date) { if (!data.anchor) return 'unknown'; const position = mod(utcDay(date) - utcDay(parseISO(data.anchor)), 15), first = Number(data.firstBreak) === 3 ? 3 : 2; const off = first === 2 ? (position >= 5 && position <= 6) || position >= 12 : (position >= 5 && position <= 7) || position >= 13; return off ? 'off' : data.vacations.includes(iso(date)) ? 'vacation' : 'work'; }
  function save() { localStorage.setItem(key, JSON.stringify(data)); }
  function openModal(id, nextOpener) { const modal = document.getElementById(id); opener = nextOpener; modal.hidden = false; document.body.classList.add('modal-open'); const first = modal.querySelector('input, textarea, button'); if (first) first.focus(); }
  function closeModal(id) { document.getElementById(id).hidden = true; document.body.classList.remove('modal-open'); if (opener) opener.focus(); }
  function upcomingRuns() {
    const today = iso(new Date()), days = [...new Set(data.vacations)].filter(value => value >= today).sort();
    return days.reduce((runs, day) => { const last = runs[runs.length - 1]; if (last && utcDay(parseISO(day)) === utcDay(parseISO(last[last.length - 1])) + 1) last.push(day); else runs.push([day]); return runs; }, []);
  }
  function resetVacationForm() { editingVacation = []; vacationForm.reset(); const today = iso(new Date()); vacationStart.value = today; vacationEnd.value = today; document.getElementById('save-vacation').textContent = 'Add vacation days'; document.getElementById('cancel-vacation-edit').hidden = true; }
  function renderVacationList() {
    const runs = upcomingRuns(); vacationList.innerHTML = '';
    if (!runs.length) { vacationList.innerHTML = '<p class="empty-vacations">No upcoming vacation days.</p>'; return; }
    runs.forEach(run => { const item = document.createElement('div'); item.className = 'vacation-list-item'; const range = run.length === 1 ? shortDate(run[0]) : `${shortDate(run[0])} – ${shortDate(run[run.length - 1])}`; item.innerHTML = `<span>${range}</span><div><button type="button" class="edit-vacation">Edit</button><button type="button" class="delete-vacation">Delete</button></div>`; item.querySelector('.edit-vacation').addEventListener('click', () => { editingVacation = run; vacationStart.value = run[0]; vacationEnd.value = run[run.length - 1]; document.getElementById('save-vacation').textContent = 'Save vacation days'; document.getElementById('cancel-vacation-edit').hidden = false; vacationStart.focus(); }); item.querySelector('.delete-vacation').addEventListener('click', () => { data.vacations = data.vacations.filter(day => !run.includes(day)); save(); renderVacationList(); render(); announce('Upcoming vacation days deleted.'); }); vacationList.append(item); });
  }
  function render() {
    title.textContent = new Intl.DateTimeFormat(undefined, { month: 'long', year: 'numeric' }).format(display);
    note.textContent = data.anchor ? `Day 1: ${new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(parseISO(data.anchor))}. Use Vacation manager for time away; select a calendar date to manage its note.` : 'Set a Day 1 work date to calculate your patrol rotation. You can still select dates to add notes.';
    grid.innerHTML = '';
    for (let blank = 0; blank < display.getDay(); blank += 1) { const cell = document.createElement('div'); cell.className = 'calendar-blank'; cell.setAttribute('aria-hidden', 'true'); grid.append(cell); }
    const last = new Date(display.getFullYear(), display.getMonth() + 1, 0).getDate(), today = iso(new Date());
    for (let day = 1; day <= last; day += 1) { const date = new Date(display.getFullYear(), display.getMonth(), day), state = stateFor(date), dateISO = iso(date), hasNote = Boolean(data.notes[dateISO]); const button = document.createElement('button'); button.type = 'button'; button.className = `calendar-day ${state}${today === dateISO ? ' today' : ''}${hasNote ? ' has-note' : ''}`; button.innerHTML = `<span class="day-number">${day}</span><span class="day-status">${state === 'unknown' ? 'Set schedule' : state === 'off' ? 'Day off' : state === 'vacation' ? 'Vacation' : 'Work'}</span>${hasNote ? '<span class="note-indicator" aria-hidden="true">●</span>' : ''}`; button.setAttribute('role', 'gridcell'); button.setAttribute('aria-label', `${dateLabel(date)}: ${state === 'unknown' ? 'schedule not set' : state}. ${hasNote ? 'Has a note. ' : ''}Open note.`); button.addEventListener('click', () => openNote(dateISO, dateLabel(date), button)); grid.append(button); }
  }
  function openNote(dateISO, label, button) { activeDate = dateISO; document.getElementById('note-title').textContent = label; document.getElementById('note-text').value = data.notes[dateISO] || ''; document.getElementById('delete-note').hidden = !data.notes[dateISO]; openModal('note-modal', button); }
  function shiftMonth(direction) { display.setMonth(display.getMonth() + direction); render(); announce(`${title.textContent}.`); }
  document.getElementById('schedule-button').addEventListener('click', event => { anchorInput.value = data.anchor; form.elements['first-break'].value = String(data.firstBreak); openModal('schedule-modal', event.currentTarget); });
  document.getElementById('vacation-button').addEventListener('click', event => { resetVacationForm(); renderVacationList(); openModal('vacation-modal', event.currentTarget); });
  document.querySelectorAll('[data-close-modal]').forEach(button => button.addEventListener('click', () => closeModal(button.dataset.closeModal)));
  document.querySelectorAll('.chart-modal').forEach(modal => { modal.addEventListener('click', event => { if (event.target === modal) closeModal(modal.id); }); modal.addEventListener('keydown', event => { if (event.key === 'Escape') closeModal(modal.id); }); });
  form.addEventListener('submit', event => { event.preventDefault(); data.anchor = anchorInput.value; data.firstBreak = Number(form.elements['first-break'].value); save(); closeModal('schedule-modal'); render(); announce('Patrol schedule saved on this device.'); });
  vacationForm.addEventListener('submit', event => { event.preventDefault(); const start = vacationStart.value, end = vacationEnd.value, updating = editingVacation.length > 0; if (end < start) { announce('Choose an end date that is on or after the start date.'); return; } const vacationDays = []; for (let date = parseISO(start); iso(date) <= end; date.setDate(date.getDate() + 1)) if (stateFor(date) !== 'off') vacationDays.push(iso(date)); if (updating) data.vacations = data.vacations.filter(day => !editingVacation.includes(day)); data.vacations = [...new Set([...data.vacations, ...vacationDays])]; save(); resetVacationForm(); renderVacationList(); render(); announce(`${vacationDays.length} vacation day${vacationDays.length === 1 ? '' : 's'} ${updating ? 'updated' : 'added'}. Regular days off were kept.`); });
  document.getElementById('cancel-vacation-edit').addEventListener('click', () => { resetVacationForm(); renderVacationList(); });
  document.getElementById('note-form').addEventListener('submit', event => { event.preventDefault(); const value = document.getElementById('note-text').value.trim(); if (value) data.notes[activeDate] = value; else delete data.notes[activeDate]; save(); closeModal('note-modal'); render(); announce(value ? 'Note saved.' : 'Note deleted.'); });
  document.getElementById('delete-note').addEventListener('click', () => { delete data.notes[activeDate]; save(); closeModal('note-modal'); render(); announce('Note deleted.'); });
  document.getElementById('previous-month').addEventListener('click', () => shiftMonth(-1)); document.getElementById('next-month').addEventListener('click', () => shiftMonth(1)); document.getElementById('today-button').addEventListener('click', () => { const now = new Date(); display = new Date(now.getFullYear(), now.getMonth(), 1); render(); announce(`${title.textContent}.`); });
  let swipeStart = null;
  document.getElementById('calendar').addEventListener('touchstart', event => { if (window.matchMedia('(max-width: 680px)').matches && event.touches.length === 1) swipeStart = event.touches[0].clientX; }, { passive: true });
  document.getElementById('calendar').addEventListener('touchend', event => { if (swipeStart === null) return; const distance = event.changedTouches[0].clientX - swipeStart; swipeStart = null; if (Math.abs(distance) > 55) shiftMonth(distance > 0 ? -1 : 1); }, { passive: true });
  function monthCanvas() {
    const canvas = document.createElement('canvas'), context = canvas.getContext('2d'), width = 1400, cellWidth = width / 7, cellHeight = 155, start = display.getDay(), last = new Date(display.getFullYear(), display.getMonth() + 1, 0).getDate(), rows = Math.ceil((start + last) / 7), height = 280 + rows * cellHeight + 70;
    canvas.width = width; canvas.height = height; context.fillStyle = '#0a071d'; context.fillRect(0, 0, width, height); context.fillStyle = '#22e6ff'; context.font = '900 28px system-ui'; context.fillText('PATROL CHART', 60, 62); context.fillStyle = '#f7f5ff'; context.font = '900 52px system-ui'; context.fillText(title.textContent, 60, 125); context.fillStyle = '#aaa3c4'; context.font = '700 19px system-ui'; ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'].forEach((day, index) => context.fillText(day, 30 + index * cellWidth, 190));
    for (let day = 1; day <= last; day += 1) { const index = start + day - 1, column = index % 7, row = Math.floor(index / 7), x = column * cellWidth + 12, y = 215 + row * cellHeight, date = new Date(display.getFullYear(), display.getMonth(), day), state = stateFor(date), dateISO = iso(date); context.fillStyle = state === 'off' ? '#bd3851' : state === 'vacation' ? '#74bd4c' : '#f7f5ff'; if (state === 'unknown') context.fillStyle = '#312b50'; context.fillRect(x, y, cellWidth - 18, cellHeight - 10); context.fillStyle = state === 'off' || state === 'unknown' ? '#fff' : '#171126'; context.font = '900 32px system-ui'; context.fillText(String(day), x + 16, y + 43); context.font = '800 16px system-ui'; context.fillText(state === 'unknown' ? 'SET SCHEDULE' : state.toUpperCase(), x + 16, y + 80); if (data.notes[dateISO]) { context.fillStyle = '#f8c743'; context.beginPath(); context.arc(x + cellWidth - 38, y + 25, 7, 0, Math.PI * 2); context.fill(); } }
    context.fillStyle = '#aaa3c4'; context.font = '600 17px system-ui'; context.fillText('Work', 60, height - 30); context.fillStyle = '#bd3851'; context.fillRect(115, height - 44, 18, 18); context.fillStyle = '#aaa3c4'; context.fillText('Day off', 150, height - 30); context.fillStyle = '#74bd4c'; context.fillRect(245, height - 44, 18, 18); context.fillStyle = '#aaa3c4'; context.fillText('Vacation', 280, height - 30); return canvas;
  }
  document.getElementById('share-button').addEventListener('click', async () => { const button = document.getElementById('share-button'), canvas = monthCanvas(); button.disabled = true; try { const blob = await new Promise(resolve => canvas.toBlob(resolve, 'image/png')); if (!blob) throw new Error('Screenshot unavailable'); const file = new File([blob], `patrol-chart-${display.getFullYear()}-${String(display.getMonth() + 1).padStart(2, '0')}.png`, { type: 'image/png' }); if (navigator.share && (!navigator.canShare || navigator.canShare({ files: [file] }))) { await navigator.share({ title: `Patrol Chart — ${title.textContent}`, text: `My patrol chart for ${title.textContent}.`, files: [file] }); announce('Month screenshot ready to share.'); } else { const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = file.name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); announce('Month screenshot downloaded so you can share it.'); } } catch (error) { if (error.name !== 'AbortError') announce('Could not prepare the month screenshot.'); } finally { button.disabled = false; } });
  render();
})();
